/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_opencvcpptest_NativeActivity */

#ifndef _Included_com_example_opencvcpptest_NativeActivity
#define _Included_com_example_opencvcpptest_NativeActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_opencvcpptest_NativeActivity
 * Method:    getEdge
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_example_opencvcpptest_NativeActivity_getEdge
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
